pipeline:
  build:
    image: rics3n/drone-ansible
    commands:
        - ansible-playbook -vvv playbook.yml -i hosts --syntax-check

  deploy:
    image: rics3n/drone-ansible
    inventory: hosts
    playbook: playbook.yml
    when:
       branch: master

