build:
    image: rics3n/drone-ansible
    commands:
        - ansible-playbook -vvv playbook.yml -i hosts --syntax-check

deploy:
  ansible:
    image: rics3n/drone-ansible
    inventory: hosts
    playbook: playbook.yml
    commands:
    when:
       branch: master

