sudo: enabled
# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

# Clean and don't fail
install:
  - wget hugo_0.26_Linux-64bit.deb
  - dpkg -i hugo_0.26_Linux-64bit.deb
  - rm -rf public || exit 0

# Build the website
script:
  - cd src
  - ../binaries/hugo --theme=ghoust

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
