baseurl = "http://pmpc.mehl.mx/"
languageCode = "en-us"
title = "Public Money, Public Code"
theme = "hugo-creative-theme"

[params]

  # You can use Markdown syntax for urls [text](//url.to/source) for
  # most longer texts.

  # All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # All projects of the portfolio are defined in their own files.
  # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
  # folder into the 'data' directory at the root of this Hugo site.
  # For more information take a look at the README.

  # To provide some metadata for search engines feel free to add some
  # information about you and your website.
  name = "Free Software Foundation Europe"
  description = "Public Money, Public Code - A campaign for releasing publicly financed software as Free Software"

  # The path must be relative to the static folder
  favicon = "favicon.ico"


  # Navigation
  [params.navigation]
    brand = "Public Money, Public Code"

    [params.navigation.links]
      about     = "About"
      reasons   = "Reasons"
      resources = "Resources"
      spread    = "Spread"
      contact   = "Contact"


  # Start banner
  [params.start]
    # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
    slogan     = "Public Money – Public Code"
    subtitle   = "Why is software that is programmed with taxpayers' money not released as Free Software? Code paid by all people should be available to all people."
    buttonText = "See the video"


  # About section
  [params.about]
    headline    = "Sounds complex? No, it's super easy!"
    description = "VIDEO"
    buttonText  = "More advantages"


  # Reasons section
  [params.reasons]
    headline = "More reasons to free public code"

  [[params.reasons.list]]
    icon = "fa-eur"
    title = "Tax savings"
    description = "Similar applications don't have to be programmed from scratch every time."

  [[params.reasons.list]]
    icon = "fa-plus"
    title = "Collaboration"
    description = "Efforts on major projects can be joint to share expertise and costs."

  [[params.reasons.list]]
    icon = "fa-users"
    title = "Serving the public"
    description = "Applications paid by the public should be available for everyone."

  [[params.reasons.list]]
    icon = "fa-lightbulb-o"
    title = "Fostering innovation"
    description = "With transparent processes others don't have to reinvent the wheel."


  # Portfolio modals
  [params.resources.modal]
    client = "Client"
    date = "Date"
    category = "Category"
    buttonText = "Close"

  # Spread the word section
  [params.spread]
    headline = "Spread the word!"
    promoText = "Obtain the latest stickers and flyers from FSFE"
    promoButtonText = "Get promo material"
    promoButtonLink = "https://fsfe.org/promo#pmpc"
    shareText = "Tell your friends and followers about Public Code"

  # Contact section
  [params.contact]
    headline = "Let's Get In Touch!"
    description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
    phone = "123-456-6789"
    email = "feedback@startbootstrap.com"
