# == ESPERANTO ==

# General strings
[Languages.eo]
  languageCode  = "eo"
  languageName  = "Esperanto"
  description   = "Publika Mono, Publika Kodo - Kampanjo por liberigi publike financitan programaron kiel Libera Programaro"
  fsdefinition  = "Libera Programaro rajtigas ĉiujn uzi, studi, kunhavigi kaj plibonigi programaron. Ĉi tiu rajto helpas subteni aliajn fundamentajn liberecojn kiel libereco de parolado, presejo kaj privateco."


# Navigation
[Languages.eo.navigation]
[Languages.eo.navigation.links]
  start     = "Eko"
  about     = "Pri"
  arguments = "Kialoj"
  action    = "Agu"
  spread    = "Spread the Word"  # TODO


# Start banner
[Languages.eo.start]
  subtitle1   = "Kial oni ne liberigas programaron kreitan per mono de impostpagantoj kiel Libera Programaro?"
  subtitle2   = "We want legislation requiring that publicly financed software developed for the public sector be made publicly available under a [Free and Open Source Software](https://fsfe.org/about/mission.html 'Free Software gives everybody the right to use, study, share and improve software. This right helps support other fundamental freedoms like freedom of speech, press and privacy.') licence. If it is public money, it should be public code as well."  # TODO
  subtitle3   = "**Kodo pagita de la popolo devus esti disponebla al la popolo!**"


# About section
[Languages.eo.about]
  headline    = "Ĉu sonas komplike? Tute ne. Estas tre facile!"
  buttonText  = "Pli da avantaĝoj"


# Arguments section
[Languages.eo.arguments]
  headline    = "Kialoj por Publika Kodo"
  followup    = "Ĉu vi opinias, ke Libera Programaro estu la defaŭlta agordo por publike financita programaro?  **Ni konvinku vian politikajn deputitojn!**"
  buttonText  = "Subskribu la Publikan Leteron"
[[Languages.eo.arguments.list]]
  icon        = "fa-eur"  # <-- do not translate this
  title       = "Impostaj ŝparadoj"
  description = "Similaj aplikprogramoj ne devas esti programita de nulo ĉiujfoje."
[[Languages.eo.arguments.list]]
  icon        = "fa-handshake-o"  # <-- do not translate this
  title       = "Kunlaboro"
  description = "Penoj de grandaj projektoj povas kunhavigi kompetentecon kaj kostojn."
[[Languages.eo.arguments.list]]
  icon        = "fa-users"  # <-- do not translate this
  title       = "Servado al la publiko"
  description = "Aplikprogramoj pagitaj de la publiko devus esti disponebla al ĉiuj."
[[Languages.eo.arguments.list]]
  icon        = "fa-lightbulb-o"  # <-- do not translate this
  title       = "Nutrado de novigado"
  description = "Kun procedoj travideblaj, aliuloj devas reinventi la radon."


# Action section
[Languages.eo.action]
  headline      = "Tell Your Representatives!"
  intro         = "In our [**open letter**](openletter/) we demand:" 
  # In "demand", please use curly quotation marks for the demand. Otherwise the build might fail: https://en.wikipedia.org/wiki/Quotation_mark
  demand        = "“Implement legislation requiring that publicly financed software developed for the public sector be made publicly available under a [Free and Open Source Software](https://fsfe.org/freesoftware/basics/summary.html 'Free Software gives everybody the right to use, study, share and improve software. This right helps support other fundamental freedoms like freedom of speech, press and privacy.') licence.”"
  description   = "**$ORGS** organisations and **$INDS** individuals already support this call for action by signing our [open letter](openletter/). You can help us make a much bigger impact by signing it, too! We will hand over all signatures to representatives all over Europe that are debating software freedom in public administration."

[Languages.eo.action.box]
  text      = "Already **$INDS SIGNATURES** – sign the open letter now!"

[Languages.eo.action.form]
  name      = "Name (required)"
  email     = "Email (required)"
  country   = "Your Country"
  zip       = "Zip Code"
  comment   = "Your comment (max. 140 characters)"
  permPriv  = "I have read and accepted the [privacy statement](privacy/)"
  permNews  = "I want to stay informed about the future of this campaign"
  permPub   = "I want my signature to appear in the [list of signatures](openletter/all-signatures)"
  submit    = "Sign Now!"


# Organisations section
[Languages.eo.organisations]
  headline  = "Supporting Organisations"
  text      = "The following organisations support our [open letter](openletter/). If your organisation is also interested in joining the call for Public Code, please [contact us](mailto:contact@fsfe.org)."


# Spread the word section
[Languages.eo.spread]
  headline          = "Spread the word!"
  promoText         = "Order the latest stickers and flyers from FSFE"
  promoButtonText   = "Get promo material"
  shareText         = "Tell your friends and followers about Public Code:"
  defaultSocialText = "If it is public money, it should be public code as well. I support this call for more public code under a Free Software licence:"


# Legal Section
[Languages.eo.legal]
  by            = "This is a campaign by Free Software Foundation Europe"
  imprint       = "Imprint"
  privacy       = "Privacy"
  transparency  = "Transparency"
  contribute1   = "The code of this website is Free Software." 
  contribute2   = "You're welcome to contribute!"
  license       = "This work is licensed under a [Creative Commons BY-SA 4.0 Licence](http://creativecommons.org/licenses/by-sa/4.0/)."


# Language selection
[Languages.eo.language]
  description = "Read this page in another language"


# 404 Error Page
[Languages.eo.error]
  headline    = "Error 404 - Page not found"
  description = "The page you're looking for does not exist."
  button      = "Back to start page"


# Specific sub-pages
[Languages.eo.subpage]
[Languages.eo.subpage.signatures]
  headline      = "Individual Open Letter Signatures"
  description   = "Below are the signatures of the signees who agreed to have their names made public. Be the next one!"
  allSignatures = "See [all public signatures](all-signatures/)."
  tableName     = "Name"
  tableCountry  = "Country"
  tableComment  = "Comment"
