# == ENGLISH ==

# General strings
[Languages.en]
  languageCode  = "en"
  languageName  = "English"
  description   = "Public Money, Public Code - A campaign for releasing publicly financed software as Free Software"
  fsdefinition  = "Free Software gives everybody the rights to use, study, share and improve software. These rights help support other fundamental freedoms like freedom of speech, press and privacy."


# Navigation
[Languages.en.navigation]
[Languages.en.navigation.links]
  start     = "Start"
  about     = "About"
  arguments = "Arguments"
  action    = "Take Action"
  spread    = "Spread"


# Start banner
[Languages.en.start]
  subtitle1   = "Why is software created using taxpayers' money not released as Free Software?"
  subtitle2   = "We want legislation requiring that publicly financed software developed for public sector must be made publicly available under a [Free and Open Source Software](https://fsfe.org/freesoftware/basics/summary.html 'Free Software gives everybody the rights to use, study, share and improve software. These rights help support other fundamental freedoms like freedom of speech, press and privacy.') licence. If it is public money, it should be public code as well."
  subtitle3   = "**Code paid by all people should be available to all people!**" 


# About section
[Languages.en.about]
  headline    = "Sounds complex? No, it's super easy!"
  buttonText  = "More advantages"


# Arguments section
[Languages.en.arguments]
  headline    = "Reasons for Public Code"
  followup    = "Do you believe that Free Software must be the default option for publicly financed software? **Then let's convince your political representatives!**"
  buttonText  = "Sign the Open Letter"
[[Languages.en.arguments.list]]
  icon        = "fa-eur"
  title       = "Tax savings"
  description = "Similar applications don't have to be programmed from scratch every time."
[[Languages.en.arguments.list]]
  icon        = "fa-handshake-o"
  title       = "Collaboration"
  description = "Efforts on major projects can be joint to share expertise and costs."  
[[Languages.en.arguments.list]]
  icon        = "fa-users"
  title       = "Serving the public"
  description = "Applications paid by the public should be available for everyone."
[[Languages.en.arguments.list]]
  icon        = "fa-lightbulb-o"
  title       = "Fostering innovation"
  description = "With transparent processes others don't have to reinvent the wheel."


# Action section
[Languages.en.action]
  headline      = "Tell Your Representatives!"
  subheadline   = "We demand: **„Implement legislation requiring that publicly financed software developed for public sector must be made publicly available under a [Free and Open Source Software](https://fsfe.org/freesoftware/basics/summary.html 'Free Software gives everybody the rights to use, study, share and improve software. These rights help support other fundamental freedoms like freedom of speech, press and privacy.') licence.“**"
  description   = "**$ORGS organisations** and **$INDS individuals** support this call for action by signing our [Open Letter](openletter/). Help us to make an impact by signing it, too! We will hand over all signatures to representatives all over Europe that are debating software freedom in public administration."

[Languages.en.action.box]
  text      = "Already **$INDS SIGNATURES** – sign the Open Letter now!"

[Languages.en.action.form]
  name      = "Name (required)"
  email     = "Email (required)"
  country   = "Your Country"
  zip       = "Zip Code"
  comment   = "Your comment (max. 140 characters)"
  permPriv  = "I have read and accepted the [privacy statement](privacy/)"
  permNews  = "I want to stay informed about the future of this campaign"
  permPub   = "I want my signature to appear in the [list of signatures](openletter/all-signatures)"
  submit    = "Sign Now!"

# Organisations section
[Languages.en.organisations]
  headline  = "Supporting Organisations"
  text      = "Following organisations support our [Open Letter](openletter/). If your organisation is also interested in joining the call for Public Code, please [contact us](mailto:contact@fsfe.org)."


# Spread the word section
[Languages.en.spread]
  headline          = "Spread the word!"
  promoText         = "Order the latest stickers and flyers from FSFE"
  promoButtonText   = "Get promo material"
  shareText         = "Tell your friends and followers about Public Code:"
  defaultSocialText = "If it is public money, it should be public code as well. I support this call for more public code under a Free Software license: "


# Legal Section
[Languages.en.legal]
  by            = "This is a campaign by Free Software Foundation Europe"
  imprint       = "Imprint"
  privacy       = "Privacy"
  transparency  = "Transparency"
  contribute1   = "The code of this website is Free Software." 
  contribute2   = "You're welcome to contribute!"
  license       = "This work is licensed under a [Creative Commons BY-SA 4.0 License](http://creativecommons.org/licenses/by-sa/4.0/)."


# Language selection
[Languages.en.language]
  description = "Read this page in another language"


# 404 Error Page
[Languages.en.error]
  headline    = "Error 404 - Page not found"
  description = "The page you're looking for does not exist."
  button      = "Back to start page"


# Specific sub-pages
[Languages.en.subpage]
[Languages.en.subpage.signatures]
  headline      = "Individual Open Letter Signatures"
  description   = "Below you find the recent signatures of people who agreed to have their signature be public. Will you be the next?"
  allSignatures = "Have a look at [all public signatures](all-signatures/)."
  tableName     = "Name"
  tableCountry  = "Country"
  tableComment  = "Comment"
