# == ENGLISH ==

# General strings
[Languages.en]
  languageCode  = "tr"
  languageName  = "Türkçe"
  description   = "Kamusal Para, Kamusal Kod - Kamu tarafından finanse edilmiş yazılımların Özgür Yazılım olarak yayınlanması için bir kampanya"
  fsdefinition  = "Özgür Yazılım herkese yazılımı kullanma, inceleme, paylaşma ve geliştirme hakkını sağlar. Bu hak ifade, basın ve mahremiyet özgürlüğü gibi diğer temel hakları desteklemeye yardımcı olur."


# Navigation
[Languages.en.navigation]
[Languages.en.navigation.links]
  start     = "Başlangıç"
  about     = "Hakkında"
  arguments = "Gerekçeler"
  action    = "Harekete Geçin"
  spread    = "Haberi Duyurun"


# Start banner
[Languages.en.start]
  subtitle1   = "Vergi verenlerin parasıyla üretilen yazılım neden Özgür Yazılım olarak yayınlanmıyor?"
  subtitle2   = "Kamu tarafından finanse edilerek kamu sektörü için geliştirilen yazılımların [Free and Open Source Software](https://fsfe.org/about/mission.html 'Özgür Yazılım herkese yazılımı kullanma, inceleme, paylaşma ve geliştirme hakkını sağlar. Bu hak ifade, basın ve mahremiyet özgürlüğü gibi diğer temel hakları desteklemeye yardımcı olur.') lisansıyla kamuya açık hale getirilmesini sağlayacak mevzuat istiyoruz. Eğer bu kamunun parasıysa o zaman kamusal kod da olmalıdır!"
  subtitle3   = "**Halkın parasıyla üretilen kod, halka açık olmalıdır!**"


# About section
[Languages.en.about]
  headline    = "Karmaşık mı geldi? Hiç de değil. Oldukça kolay!"
  buttonText  = "Daha fazla avantaj"


# Arguments section
[Languages.en.arguments]
  headline    = "Kamusal Kod için Gerekçeler"
  followup    = "Kamu tarafından finanse edilen yazılımın standart seçeneğinin Özgür Yazılım olmasına mı inanıyorsunuz? **O zaman politik temsilcinizi ikna edelim!**"
  buttonText  = "Açık Mektubu İmzalayın"
[[Languages.en.arguments.list]]
  icon        = "fa-eur"  # <-- do not translate this
  title       = "Vergi tasarrufu"
  description = "Benzer uygulamalar her seferinde sıfırdan üretilmek zorunda olmayacaktır."
[[Languages.en.arguments.list]]
  icon        = "fa-handshake-o"  # <-- do not translate this
  title       = "İşbirliği"
  description = "Büyük projelerdeki çabalar uzmanlığı ve maliyeti paylaşabilirler."
[[Languages.en.arguments.list]]
  icon        = "fa-users"  # <-- do not translate this
  title       = "Halka hizmet"
  description = "Kamunun ödediği uygulamalar, herkesin erişimine açık olmalıdır."
[[Languages.en.arguments.list]]
  icon        = "fa-lightbulb-o"  # <-- do not translate this
  title       = "Yenilikçiliği teşvik"
  description = "Şeffaf süreçlerle başkalarının tekerleği yeniden icat etmesi gerekmez."


# Action section
[Languages.en.action]
  headline      = "Milletvekilinize Söyleyin!"
  intro         = "[**Açık mektubumuzda**](openletter/) şunu talep ediyoruz:"
  # In "demand", please use curly quotation marks for the demand. Otherwise the build might fail: https://en.wikipedia.org/wiki/Quotation_mark
  demand        = "“Kamu tarafından finanse edilerek kamu sektörü için geliştirilen yazılımların [Free and Open Source Software](https://fsfe.org/freesoftware/basics/summary.html 'Özgür Yazılım herkese yazılımı kullanma, inceleme, paylaşma ve geliştirme hakkını sağlar. Bu hak ifade, basın ve mahremiyet özgürlüğü gibi diğer temel hakları desteklemeye yardımcı olur.') lisansıyla kamuya açık hale getirilmesini sağlayacak mevzuatı yürürlüğe koyun.”"
  description   = "Şu ana kadar **$ORGS** örgüt ve **$INDS** kişi bu eylem çağrısına desteğini [açık mektubumuzu](openletter/) imzalayarak sundu. Siz de imzalayarak daha büyük bir etki yaratmamıza yardımcı olabilirsiniz. Bütün bu imzaları, Avrupa çapındaki kamu kurumlarında yazılım özgürlüğünü tartışan milletvekilerine sunacağız."

[Languages.en.action.box]
  text      = "Şimdiye kadar **$INDS SIGNATURES** – açık mektubu şimdi imzalayın!"

[Languages.en.action.form]
  name      = "Ad-Soyad (gerekli)"
  email     = "E-posta (gerekli)"
  country   = "Ülke"
  zip       = "Posta Kodu"
  comment   = "Görüşler (en fazla 140 karakter)"
  permPriv  = "[Gizlilik beyanını](privacy/) okudum ve onaylıyorum"
  permNews  = "Kampanya hakkında haber almak istiyorum"
  permPub   = "Adımın [imzacılar listesinde](openletter/all-signatures) gözükmesini istiyorum"
  submit    = "İmzala!"


# Organisations section
[Languages.en.organisations]
  headline  = "Destekleyen Örgütler"
  text      = "Aşağıdaki örgütler [açık mektubumuzu](openletter/) destekliyorlar. Eğer sizin de örgütünüz Kamusal Kod çağrısına katılmakla ilgileniyorsa, lütfen [bizimle bağlantıya geçin](mailto:contact@fsfe.org)."


# Spread the word section
[Languages.en.spread]
  headline          = "Haberi Duyurun!"
  promoText         = "FSFE'den en güncel çıkartma ve broşürleri sipariş edin"
  promoButtonText   = "Tanıtım malzemesi iste"
  shareText         = "Arkadaş ve takipçilerinize Kamusal Kodu söyleyin:"
  defaultSocialText = "Eğer bu kamunun parasıysa o zaman kamusal kod da olmalıdır. Daha fazla kamusal kodun Özgür Yazılım lisansı kapsamına alınması çağrısını destekliyorum:"


# Legal Section
[Languages.en.legal]
  by            = "Bu Avrupa Özgür Yazılım Vakfı'nın bir kampanyasıdır"
  imprint       = "Imprint"
  privacy       = "Mahremiyet"
  transparency  = "Şeffaflık"
  contribute1   = "Bu web sitesinin kodu Özgür Yazılımdır."
  contribute2   = "Katkı verebilirsiniz!"
  license       = "Bu çalışma [Creative Commons BY-SA 4.0 Lisansı](http://creativecommons.org/licenses/by-sa/4.0/) kapsamındadır."


# Language selection
[Languages.en.language]
  description = "Bu sayfayı başka bir dilde okuyun"


# 404 Error Page
[Languages.en.error]
  headline    = "Error 404 - Sayfa bulunamadı"
  description = "Aradığınız sayfa mevcut değil."
  button      = "Başlangıç sayfasına dönün"


# Specific sub-pages
[Languages.en.subpage]
[Languages.en.subpage.signatures]
  headline      = "Bireysel Açık Mektup İmzaları"
  description   = "Aşağıdaki imzalar, isimlerini herkese açık yapmayı kabul edenlerdir. Bir sonraki siz olun!"
  allSignatures = "[Bütün herkese açık imzaları](all-signatures/) görüntüleyin."
  tableName     = "İsim"
  tableCountry  = "Ülke"
  tableComment  = "Görüş"
